#!/bin/sh
usage="Usage: loadicons [-hV] [-c|-C] [-i|-p|-P] [-U FILE|UPTIME] [-X COMMAND]"

help() {
  bars=' ▁ ▂ ▃ ▄ ▅ ▆ ▇ █'	no_color="same as \`NO_COLOR=1 ${0##*/} …\`"
  if [ "${CLICOLOR:-0}" != 0 ]; then
    c=" $e[38;5"
    bars="$c;46m▁$c;154m▂$c;226m▃$c;220m▄$c;214m▅$c;208m▆$c;202m▇$c;196m█$e[39m"
    proc_loadavg="$e[32m$proc_loadavg$e[m"
    if [ "$hovertext" = 1 ]; then
      no_color="respects ${href}https://no-color.org/$htext\$NO_COLOR$h0"
    fi
  fi

  cat <</help
Show a summary of system load, with color and bar icon support
$usage
  -c, --color          Color output by load level (default: auto-detect)
  -C, --color=never    Disable colors ($no_color)
  -d, --delim=STRING   Delimiter (default: space if --icons or else comma space)
  -h, --help           Show this help
  -H, --no-hovertext   Disable hover text (otherwise present alongside colors)
  -i, --icons          Output as bars, from blank to one of:$bars
  -p, -%, --percent    Show load as percent across CPUs (load * 100 / cores)
  -P, --processes      Show counts of waiting proceses (default, as \`uptime\`)
  -T, --tmux-colors    Issue tmux color codes instead of ANSI SGR colors
  -U, --uptime=FILE    Load averages (line 1 fields 1-3; default: $proc_loadavg)
  -U, --uptime=UPTIME  Manually specify load averages (quoted spaced trio)
  -V, --version        Show this script's version info
  -X, --exec=COMMAND   Uptime command (line 1 fields 10, 11, 12)

Install in tmux with a line like \`set -g status-right '#(${0##*/} -iTd "")\`

/help
  version
}

# This script was inspired by https://github.com/jdx/tmux-cpu-info

version() {
  url="https://github.com/adamhotep/misc-scripts"
  echo "Part of ${hovertext:+$href$url$htext}misc-scripts$h0, $url"
  echo "loadicons 0.1.20260711.0, Copyright 2026+ by Adam Katz, GPLv3+"
  exit
}

die() { printf '%s\n' "$@" >&2; exit ${exit:-2}; }

needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }


if [ -n "$NO_COLOR" ]; then
  CLICOLOR=
elif [ -n "$CLICOLOR_FORCE" ] || [ -t 1 ]; then
  CLICOLOR=1
else
  CLICOLOR=0
fi

avg="$proc_loadavg"
action=file
if [ ! -f "$avg" ]; then
  avg=uptime
  action=cmd
fi
delim=default$$
help=
hovertext=1
out=P	# default to waiting processes
proc_loadavg="/proc/loadavg"
tmux_colors=
while getopts cCd:hHipPTU:vVX:%-: OPT; do
  if [ "$OPT" = - ]; then # long opt https://stackoverflow.com/a/28466267/519360
    OPT="${OPTARG%%=*}"    OPTARG="${OPTARG#"$OPT"}"    OPTARG="${OPTARG#=}"
  fi
  case $OPT in
    ( c | color )	[ "$OPTARG" != "${OPTARG#[Nn0]}" ]; CLICOLOR=$? ;;
    ( C | nocolor )	CLICOLOR= ;;
    ( d | delim* )	delim="$OPTARG" ;;	# no `needs_arg`, blank is okay
    ( h | help )	help=1 ;;
    ( H | *hover* )	hovertext= ;;
    ( i | icon* )	out=i ;;
    ( [p%] | p*c*t )	out=p ;;
    ( P | proc* )	out=P ;;
    ( T | tmux* )	tmux_colors=1 CLICOLOR=1 ;;
    ( U | uptime )	needs_arg; avg="$OPTARG"
    			[ -f "$avg" ] && action=file || action=string ;;
    ( [vV] | ver* )	version ;;
    ( X | exec* )	needs_arg; avg="$OPTARG" action=cmd ;;
    ( \? )		die "$usage" ;;
    ( * )		die "Illegal option --$OPT" "$usage" ;;
  esac
done

e= href= htext= h0=
if [ "${CLICOLOR:-0}" != 0 ]; then
  e=''
  # OSC 8: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
  # tmux.conf needs `set -as terminal-features ",*:hyperlinks"`
  # as noted in https://stackoverflow.com/a/79306046/519360
  # Use like this: ${href}LINK_TARGET${htext}TEXT$h0
  if [ "$hovertext" = 1 ]; then
    if [ "$tmux_colors" = 1 ]; then
      # NOTE, I can't get this working on the status line, so it's disabled
      case "$(tmux -V)" in
        ( *\ [012].* | *\ 3.[0-3] )	hovertext= ;;	# unsupported version
        #( *\ 3.* )	href='#[link=' htext=']' h0="$href$htext" ;;
        ( * )		hovertext= ;;	# unknown version
      esac
    else
      href="$e]8;;" htext="$e\\" h0="$href$htext"
    fi
  fi
fi

if [ "$help" = 1 ]; then help; fi

if [ "$delim" = "default$$" ]; then
  if [ "$out" = i ]; then
    delim=' '
  else
    delim=', '
  fi
fi

getconf NPROCESSORS_ONLN |awk -v avg="$avg" -v action=$action -v out="$out" \
  -v color="$CLICOLOR" -v tmux_colors="$tmux_colors" -v OFS="$delim" \
  -v hovertext="$hovertext" -v href="$href" -v htext="$htext" -v h0="$h0" \
'
  function colorize(code) {
    if (!color) return ""
    if (code == 39) {
      if (tmux_colors) return "#[fg=default]"
    } else { code = "38;5;" code }
    if (tmux_colors) return sprintf("#[fg=colour%d]", code)
    return sprintf("%c%c[%sm%c", 1, 27, code, 2)
  }
  function render(num, min) {
    pct = num * 100 / cores
    o = ""
    if (hovertext) {
      o = sprintf("%s%smin load avg: %.2f = %.1f%%%s",
        href, o min, num, pct, htext)
      if (tmux_colors) o = href "http://example.com" htext
    }
    if      (out == "i") i = 1
    else if (out == "p") num = sprintf("%.1f%%", pct)
    else num = sprintf("%.2f", num)

    if      (pct <   5) o = o colorize(51)	(i ? " " : num)
    else if (pct <  10) o = o colorize(46)	(i ? "▁" : num)
    else if (pct <  20) o = o colorize(154)	(i ? "▂" : num)
    else if (pct <  40) o = o colorize(226)	(i ? "▃" : num)
    else if (pct <  60) o = o colorize(220)	(i ? "▄" : num)
    else if (pct <  80) o = o colorize(214)	(i ? "▅" : num)
    else if (pct < 100) o = o colorize(208)	(i ? "▆" : num)
    else if (pct < 500) o = o colorize(202)	(i ? "▇" : num)
    else		o = o colorize(196)	(i ? "█" : num)

    return o colorize(39) h0
  }
  {
    cores = $1
    if (action == "cmd") { avg | getline; $1 = $10; $2 = $11; $3 = $12; }
    else if (action == "file") { getline < avg }
    else { split(avg, a); $1 = a[1]; $2 = a[2]; $3 = a[3] }

    print render($1, 1), render($2, 5), render($3, 15)
  }
'
