#!/usr/bin/perl
# This script is released under the GNU GPL 2+, copyright (c) 2005+ by Adam Katz
# See the timecalc_help function below for description
use strict;
use warnings;

my $tcPROGRAM = "timecalc";
my $tcVERSION = "0.7.20260607.0";
sub timecalc_usage { return "Usage: $tcPROGRAM [OPTIONS] [TIME|SECONDS]..."; }

my $min = 60; my $hour = 60*$min; my $day = 24*$hour; my $year = 365*$day;

sub timecalc_help {
  print "Convert time between colon-delimited units and numbers of seconds.\n";
  print timecalc_usage();
  print '
  TIME     Colon-separated time including seconds or a specified smallest unit
           Format is Y:D:H:M:S, 365.0 days/year (ignores leap years)
  SECONDS  A number of seconds
  <STDIN>  If run without arguments, lines from standard input are used instead
  OPTIONS
    --human   Output the time with human-readable units
    --seconds Output time in seconds regardless of input
    --time    Output colon-delimited time regardless of input

Units indicate smallest value; 3h & 3:00m & 3:00:00 will all return 10800.
Yes, you can hack this to do conversions for you, like 85:3.1m (3d 13h 3m 6s).

Returns: opposite of argument (TIME->SECONDS, SECONDS->TIME)
Valid Range:  0-2147483647 or 0-68:35:03:14:07 (assuming 32bit limit)
64bit Max:  9223372036854775807 or 292471208677:195:15:30:07 (9.22Es, 292Gy)';
  print "\n\n";
  timecalc_version();
  # timecalc 0.2 was written in /bin/sh ... in less code, though this is faster
  exit 0;
}

sub timecalc_version {
  print "Part of misc-scripts: https://github.com/adamhotep/misc-scripts\n";
  print "$tcPROGRAM $tcVERSION, Copyright 2005+ by Adam Katz, GPLv2+\n";
  exit 0;
}

# Tests {{{

# test_timecalc: string|number number|string -> boolean
# takes in an argument for timecalc and reports if its result was the other arg
sub test_timecalc {
  my ($value, $answer, $option) = @_;
  my $result = timecalc($value, $option // "");
  if ($result =~ /^$answer$/) { return 1; }
  $value .= " (as $option)" if $option;
  print STDERR "Test of $value failed. Computed $result, should be $answer.\n";
  return 0;
}

# timecalc_testsuite: VOID -> VOID
# Test suite for timecalc, prints tests that failed or reports that none failed
sub timecalc_testsuite {
  # multiply to prevent short-circuit (which would only show first failure)
  if ( test_timecalc(5, "0:05")
     * test_timecalc("0:66", 66)
     * test_timecalc("67s", "1:07")
     * test_timecalc("1:30", 90)
     * test_timecalc("2h", 7200)
     * test_timecalc("3d", 259200)
     * test_timecalc(1440, "24:00")
     * test_timecalc("3:00:89", 10889)
     * test_timecalc("-1:4:93", "-" . timecalc("1:4:93"))
     * test_timecalc(-126410465, "-4:3:02:01:05")
     * test_timecalc("65.5h", "235800")
     * test_timecalc("65h30m", "235800")
     * test_timecalc("5595", "5595", "seconds")
     * test_timecalc("55:95", "56:35", "time")
     * test_timecalc("55h95m", "203700")
     * test_timecalc("55h95m", "2:08:35:00", "time")
     * test_timecalc("5595", "1:33:15", "time")
     * test_timecalc("18305.5", "5:05:05.5")
     * test_timecalc("12w 12:34:56", "7302896")
     * test_timecalc("12y 12:34", "378477240")
  ) { print "All tests completed successfully.\n"; exit 0; }
  else { print "At least one test failed.\n"; exit 1; }
}

# end tests }}}

# timecalc_err: string -> VOID
# report that string is bad, suggest help
sub timecalc_err {
  print STDERR "$tcPROGRAM: `@_' is neither a time nor a number of seconds.\n";
  print STDERR timecalc_usage();
  print STDERR "Try `$tcPROGRAM --help' for more information.\n";
}

# There are sooo many ways to represent a number. This gets most (in radix 10).
my $num_re = '(?= \.? [0-9] ) [0-9]* (?: \. [0-9]* )? (?: [Ee] [+-]? [0-9]+ )?';

sub human2time {
  $_ = shift @_;

  # collapse weeks into days
  s@ ( $num_re ) ( \s* ) w (?: ( $num_re ) \s* d )?
   @ ( ($3 // 0) + $1 * 7) . $2 . "d"
   @ex;

  # allow for colon-delimited H:M or H:M:S
  s@ ( [yd] \s* $num_re ) : ( $num_re ) (?: : ( $num_re ) )? \s* $
   @ sprintf("%sh%sm%ss", $1, $2, $3 // 0)
   @ixe;

  @_ = m@
    ^
    \s*+
    (?= \S )
    (?: ( $num_re ) \s* y \s* )?
    (?: ( $num_re ) \s* d \s* )?
    (?: ( $num_re ) \s* h \s* )?
    (?: ( $num_re ) \s* m \s* )?
    (?: ( $num_re ) \s* s \s* )?
    $
  @ix;
  return $_ unless @_;
  $_ = join(":", map { $_ // "0" } @_);
  s/^[0:]+//;	# strip leading zeroed fields
  return $_;
}

sub time2sec {
  my ($time) = @_;
  my $temp = $time;
  $time = 0;
  foreach my $field (1, $min, $hour, $day, $year) {
    $_ = $temp;
    s/.*?([^:]+)$/$1/;
    $temp =~ s/^(.*?):?[^:]+$/$1/;
    if ($_ =~ /./) { $time = $time + ($field * $_); }
  }
  print STDERR "Ignored fields larger than years, $temp\n" if $temp =~ /./;
  return $time;
}

sub sec2time {
  my ($time, $option) = @_;
  my ($years, $days, $hours, $mins, $secs);
  $time -= $year * ($years = int ($time/$year));
  $time -= $day  * ($days  = int ($time/$day));
  $time -= $hour * ($hours = int ($time/$hour));
  $time -= $min  * ($mins  = int ($time/$min));
  my $template = "%d:%d:%02d:%02d:%06.3f";
  if ($option eq "human") { $template = "%dy %dd %dh %dm %.3f"; } # add s later
  $time = sprintf($template, $years, $days, $hours, $mins, $time);
  $time =~ s/^[0:ydhm ]*(.+[:ydhm ].+?)\.?0*$/$1/;  # remove lead & tail zeros
  if ($option eq "human") {
    $time .= "s" if $time =~ /[0-9]$/;
    $time =~ s/(?<![0-9])[0dhms ]+$//;	# remove trailing empty units
  }
  return $time;
}

# timecalc: string|number [time|seconds] -> number|string
# Convert a colon-separated time to its value in seconds or vice-versa, units ok
sub timecalc {
  my $output = "";
  my $time = shift;
  my $option = shift // "";

  # Accept -t/--time and -s/--seconds to force the output
  if ($option eq "human")	{ $output = "time"; }
  elsif ($option eq "time")	{ $output = "time"; }
  elsif ($option eq "seconds")	{ $output = "seconds"; }
  elsif ($option ne "") 	{ die "invalid option $option\n"; }

  # use the first line of input if no data was passed from the command line
  if ($time eq "") { $time = <STDIN>; }

  my $neg = "";

  # negative values are noted, removed, and prepended to end result
  if ($time =~ /^-[0-9]/) { $neg="-"; $time =~ s/^-(.*)$/$1/; }

  # support mixes of named units and colon-delimited predecessors
  $time =~ s/ : ( $num_re \s* s ) /m$1/x;
  $time =~ s/ : ( $num_re \s* m ) /h$1/x;
  $time =~ s/ : ( $num_re \s* h ) /d$1/x;
  $time =~ s/ : ( $num_re \s* d ) /y$1/x;

  # HUMAN -> TIME
  my $orig_time = $time;
  $time = human2time($time);	# direct mapping (not cleaned yet)
  if ($orig_time ne $time and $option ne "") {
    if ($orig_time =~ /[ydhm][0-9]/) { $output ||= "seconds" }
    else { $output ||= "time" }
  }

  # TIME -> SECONDS
  if ($time =~ / ^ $num_re (?: : $num_re )+ $ /x) {
    $time = time2sec($time);
    $time = sec2time($time, $option) if $output =~ /time/;  # --time forced
  }

  # SECONDS -> TIME
  elsif ($time =~ / ^ $num_re $ /x) {
    $time = sec2time($time, $option);
    $time = time2sec($time) if $output =~ /seconds/;  # --seconds forced
  }

  # INVALID INPUT
  else { return undef; }

  return "$neg$time";
}


##################################
# the above could be a library if we rip out the following
# and put it in a script with a Require line referencing the library

use Getopt::Long qw(:config no_ignore_case bundling);
my %opt = ();
my $o = "";
if (-t 0 and @ARGV == 1 and $ARGV[0] eq "-h") { timecalc_help(); exit 0; }
GetOptions(\%opt, qw/ help version|ver|V|v human|h seconds|s test time|t /);
if ($opt{help}) 	{ timecalc_help();	exit 0; }
if ($opt{version})	{ timecalc_version();	exit 0; }
if ($opt{test}) 	{ timecalc_testsuite();	exit 0; }

if ($opt{human})	{ $o = "human"; }
if ($opt{seconds})	{ $o = "seconds"; }
if ($opt{time}) 	{ $o = "time"; }

$tcPROGRAM = $0 =~ s/.*\///r;
for (@ARGV ? @ARGV : <>) {
  my $time = timecalc($_, $o);
  if (defined $time) { print "$time\n"; }
  else { timecalc_err($_); exit 1; }
}
