#!/bin/bash
# This uses bash for arrays, pattern substitution, and $'...' ANSI C quoting

help() { cat <</help
Usage: ${0##*/} [OPTIONS] [--] 'PROGRAM TEXT' [ASSIGNMENT...] [FILE...]
       ${0##*/} [OPTIONS] -f PROGRAM_FILE [-f...] [--] [ASSIGNMENT...] [FILE...]
Decompress input(s) and pass to awk with proper FILENAME, FNR, and NR variables.
This works IN-LINE so you can stream things properly.

  --awk=COMMAND  Use COMMAND instead of \`awk\` (not in mawk)
  -F REGEX       Set the field separator, FS, to REGEX (like \`-v FS=REGEX\`)
  -f FILE        Program text is read from FILE instead of command line
  -v VAR=VALUE   Creates awk variable VAR and assigns VALUE to it
  --             This is the final option
  FILE           A file to process (default is \`-\`, which is \`/dev/stdin\`)
  ASSIGNMENT     As -v but potentially after running FILE(s)
                 WARNING: Delayed assignment is not implemented yet

Extra awk variables:
  UNZIPPER       The command used to decompress the current FILENAME

BUG1: If a piped input is EXACTLY 15 bytes, this will awkwardly wait for more.
BUG2: ASSIGNMENTs cannot be made between reading FILEs. They're all made first.
BUG3: GNU/gawk's \`nextfile\` and other file-specific extensions won't work.

/help
  version
}

version() {
  echo "Wraps awk ($("$awk" --version 2>/dev/null |grep -m1 '[0-9]' \
    || echo "'$awk' does not appear to report its own version"))"
  echo "Part of misc-scripts: https://github/adamhotep/misc-scripts"
  echo "zawk 0.4.20260315.0 Copyright 2010+ by Adam Katz, Apache License 2.0"
  exit
}

# Usage: warn MESSAGE
# Report 'zawk: MESSAGE' to standard error
warn() {
  echo "${0##*/}: ${*:-WARNING}" >&2
}

# Usage: die MESSAGE
# As `warn MESSAGE` but also exit everything with an error code
die() {
  warn "${*:-ABORTING}"
  exit 2
}

# Usage: _mktemp
# A safe temporary file (some versions of mktemp may not support the structure)
_mktemp() {
  command mktemp "$@" "${TMPDIR:-/tmp}/zawk-$$.XXXXXX" 2>/dev/null \
    || command mktemp "$@" 2>/dev/null
}
# Usage: mktemp
# make a temporary file and save it to the list of temp files to be deleted
mktemp() {
  local t="$(_mktemp "$@")"
  echo "$t" |tee -a "$tempfiles"
}
export tempfiles="$(_mktemp)"	# we can't use mktemp here
echo "$tempfiles" > "$tempfiles"
cleanup() { awk '{ printf("%s%c", $0, 0) }' $tempfiles |xargs -0 rm -f; }
trap cleanup 0 1 2 3 4 5 6 9 11 15 18

# Usage: we_have COMMAND[...]
# True when we have all given command(s). No output.
we_have() {
  command -v "$@" >/dev/null 2>&1
}

# Usage: find_unzipper FILE
# Name the utility that can unzip given FILE, die if we don't have it
find_unzipper() {
  local unzipper=cat
  case "$(file - < "${1:-/dev/stdin}")" in
    ( *": bzip2 "* )	unzipper=bunzip2 ;;
    ( *": compress'd"*) unzipper=uncompress ;;
    ( *": gzip "* )	unzipper=gunzip ;;
    ( *": LZ4 "* )	unzipper=unlz4 ;;
    ( *": LZMA "* )	unzipper=unlzma ;;
    ( *": XZ "* )	unzipper=unxz ;;
    ( *": zlib "* )	unzipper=gunzip ;;
    ( *": Zip "* )	unzipper=gunzip ;;	# what about multi-file zips?
    ( *": Zstandard "*) unzipper=unzstd ;;
    ( *": data" )	unzipper=gunzip ;;	# zip is messy, assume it here
  esac
  if ! we_have "$unzipper"; then
    die "could not find '$unzipper' to decompress '$1'"
  fi
  echo "$unzipper"
}

# not posix but present nearly everwhere (GNU coreutils, BSD). Fallback:
if ! we_have readlink; then
  # Usage: readlink [-f] LINK
  # Print the target of given LINK, keep following given -f, limit=100 (~0.33s)
  readlink() {
    local canonicalize= file="$1" target= i=0
    case "$1" in ( -f | --canonicalize ) canonicalize=1 file="$2" ;; esac
    if [[ $file != /* ]]; then file="$PWD/$file"; fi
    while [[ -L "$file" && "$((i+=1))" -le 100 ]]; do
      target="$(ls -dl "$file")" || break
      target="${target#* $file -> }"
      if [[ "$target" != /* ]]; then target="${file%/*}/$target"; fi
      if [[ -e "$target" ]]; then file="$target"; else break; fi
      if [[ -z "$canonicalize" ]]; then break; fi
    done
    echo "$file"
  }
fi

# Usage: shorten FILE
# Show the most concise location for FILE, relative is okay
shorten() {
  local pth="$1" up="${PWD%/*}" up2="${PWD%/*/*}" rp pr
  up="../${1#$up/}" up2="../../${1#$up2/}"
  if we_have realpath; then	# full relative path to present working dir
    rp="$(realpath --relative-to="$PWD" "$1" 2>/dev/null)"
  fi
  if [ "${BASH_VERSION#4.[4-9]}" != "${BASH_VERSION#[5-9].}" ]; then # 4.4 - 9.9
    pr="${1%/*}"
    if [ -d "$pr" ]; then
      pr="$(cd "$pr"; pr="\w"; echo "${pr@P}/${1##*/}")" # bash prompt abbrev
    else
      pr="$1"
    fi
  fi
  for P in "${1#$PWD/}" "~/${1#$HOME/}" "$up" "$up2" "$rp" "$pr"; do
    # Note, -ef (same device & inode) is bash/dash/zsh/ksh but not POSIX
    # Tested with `[[ /dev/stdin -ef "$(readlink -f /dev/stdin)" ]]`
    #  * works on bash+udev  (Bash 5.0.11, Linux 5.3.0)
    #  * FAILS on bash+devfs (Bash 4.4.23, FreeBSD 11.2)
    if [ "${#P}" -lt "${#pth}" ] && [ "$P" -ef "$pth" ] 2>/dev/null; then
      pth="$P"
    fi
  done
  echo "$pth"
}

# Usage: unlink LINK
# Traverse LINK up to two levels and make the result nicer-looking
unlink() {
  local F2= F="$(readlink "$1")"
  F2="$(readlink "${F:=$1}")"
  F="${F2:-$F}"
  case "${F:=$1}" in
    ( /proc/self/* )	F="${F#/proc/self/}" ;;	# /proc/self/fd/0 -> fd/0
    ( /dev/fd/* ) 	F="${F#/dev/}" ;;	# /dev/df/0 -> fd/0
    ( * )		F="$(shorten "$F")" ;;
  esac
  echo "${F:-$1}"
}

# Usage: decompress FILE
# Print file metadata (see $file_keeper later) and the decompressed FILE
decompress() {
  local unzipper file="${1:--}" filename="${1:--}" retval
  : "decompress $*"
  if [ "$file" = "-" ]; then file=/dev/stdin; fi

  # character device, named pipe, or symlink to either
  if [ -c "$file" ] || [ -p "$file" ]; then
    # This used to save the contents in a variable, but we can't save NUL chars
    if [ -z "$head" ]; then head="$(mktemp)"; fi
    head -c15 "$file" > "$head"  # save first 15 bytes to examine for file type
    unzipper="$(find_unzipper "$head")"
    filename="$(unlink "$file")"
    # BUG3 - To implement `nextfile`, background the unzipper and pass its PID
    # on this line (so we can kill it from awk). Problem: we don't know it yet!
    printf "%s%s%s%s\n" "$_zawk_fs" "$filename" "$_zawk_d" "$unzipper" #metadata
    {
      cat "$head"			# put back those first 15 bytes
      if [ "$(wc -c < "$head")" -ge 15 ]; then	# only if we read 15 bytes
        : 'BUG1 - we are running `cat` assuming there is a 16th byte to read'
        # This is a minimal risk; a blank gzip is 20B and blank xz is 32B
        cat "$file"			# read the rest of the pipe
      fi
    } | "$unzipper"
    retval=$?
    file="$filename"	# correct FILE name for the warning given exit code 1

  else	# input is a file or something that we'll let the decompressor error on
    unzipper="$(find_unzipper "$file")"
    if [ "$file" = "/dev/stdin" ]; then
      filename="$(unlink "$file")"
    fi
    printf "%s%s%s%s\n" "$_zawk_fs" "$filename" "$_zawk_d" "$unzipper" #metadata
    "$unzipper" < "$file"
    retval=$?
  fi

  # some debug information (run me as `bash -x zawk ...`)
  case $retval in
    ( 0 )	:    "decompressor exited normally (success)" ;;
    ( 1 )	warn "Warning: error decompressing '$file'" ;;
    ( 141 )	:    "decompressor prematurely truncated" ;;
    ( * )	:    "unknown decompressor error $retval" ;;
  esac
  return $retval
}

# Usage: program_file
# Push the file_keeper metadata handler code as a program-file before others
program_file() {
  if [ -z "$program_file" ]; then
    program_file="$(mktemp)"
    echo "$file_keeper" > "$program_file"
    opts+=(-f "$program_file")
  fi
}

# Usage: valid_assignment STRING
# True when given a valid awk assignment, exit with error when not
valid_assignment() {
  var="${1%%=*}"
  # there is an `=` and $var neither starts with a digit nor has an invalid char
  [ "$var" != "$1" ] && [ "${var#[0-9]}" = "${var#*[^A-Za-z_0-9]}" ]
  return $?
}

# AWK code to handle metadata and control FILENAME, FNR, NR and UNZIPPER:
# If the first 2 chars are _ZAWK_FS && split the rest by _ZAWK_D with > 1 field:
#   If not on the first line ever, save FILENAME and UNZIPPER in ZAWK_DATA
#   Set FILENAME to the first field; set UNZIPPER to the second field
#   Set the file's number of records (FNR) to zero so line 1 increments properly
#   Decrement the overall number of records (NR) because this one is metadata
#   Done with metadata line, advance to line FNR=1 of this input
# (No, this is not a problem if it precedes a BEGIN clause or function.)
#
# BUG3 - aside from the chicken & egg problem noted in decompress(), this would
# simply be a new function (put on line one):
#     function nextfile() { system("kill " ZAWK_DATA[3]); }
file_keeper='
  substr($0, 1, 2) == _ZAWK_FS && split(substr($0, 3), ZAWK_DATA, _ZAWK_D) > 1 {
    if (NR > 1) { ZAWK_DATA[-1] = FILENAME; ZAWK_DATA[-2] = UNZIPPER; }
    FILENAME = ZAWK_DATA[1];
    UNZIPPER = ZAWK_DATA[2];
    FNR = 0;
    NR--;
    getline
  }
' # WARNING, THE ABOVE AWK CODE IS COLLAPSED INTO ONE LINE. DO NOT ADD COMMENTS!

declare -a opts
_zawk_fs=$'\x1c\x01'	# file separator, start-of-heading
_zawk_d=$'\x02\x1f'	# delimiter: start-of-text, unit separator
awk="awk"
program_text= program_file= tmp=

# most of these options are from gawk and will cause an error in other awks
while getopts bcCd:D:e:E:f:F:ghi:l:L:MnNo:Op:PrsStv:VW:-: OPT; do
  case "$OPT$OPTARG" in
    h|[-W]help* ) help ;;
    [-W]usage )	help |awk '$1 == "Decompress" { exit } 1'; exit ;;
    [-W]vers* )	version ;;
    -awk=?* )	awk="${OPTARG#*=}" ;;
    -awk* )	die "option --awk=COMMAND lacks a COMMAND" ;;
    - ) 	break ;;
    f*|-file=?* ) program_file; opts+=("-$OPT$OPTARG") ;;
    \? )	die ;;	# (error already provided by getopts)
    v* )	valid_assignment "$OPTARG" || die "improper assignment: $OPTARG"
    		opts+=("-$OPT$OPTARG") ;;
    F ) 	opts+=("-$OPT" "$OPTARG") ;;	# support an empty FS
    * ) 	opts+=("-$OPT$OPTARG") ;;
  esac
done	# the shift command for getopts is later
shift $((OPTIND-1))

if ! we_have "$awk"; then
  die "Invalid awk command '$awk'"
fi

# push _zawk_fs and _zawk_d variables into awk
opts+=(-v _ZAWK_FS="$_zawk_fs" -v _ZAWK_D="$_zawk_d")

# If no program file (which we'd have already populated), append the command
if [ -z "$program_file" ]; then
  n=$'\n'	# pure newline; ${A//\n/} fails but ${A//$n/} works
  # Metadata handler is on one line so awk errors have the right line numbers
  program_text="${file_keeper//$n/}	${1:-1}"
  shift
fi

# awk also allows an ASSIGNMENT instead of a FILE:
while [ -n "$1" ] && valid_assignment "$1"; do
  : "while valid_assignment $1"
  opts+=(-v "$1")
  shift
done

# BUG2: ASSIGNMENTs _between_ FILEs don't work. For example, we can't do this:
#     $  date |awk 'FNR < 2 { print x, y, $0 }' x=1 - y=2 test
#     1  Thu 06 Jun 2019 05:49:09 PM EDT
#     1 2 test file output
# I can add assignments in the file metadata, but awk doesn't have `eval` (or
# anything safer), so the best I'd be able to do is to create a new associative
# array and convert e.g. `x=1` into `ZAWK[x] = 1`
#
# Instead, this seeks assignments, sets them, and prunes them from the FILE list
been_there=0
for argument in "$@"; do
  : "for \$argument=$argument \$@=$@"
  if [ "$been_there" = 0 ]; then
    unset been_there
    set --
  fi
  if valid_assignment "$argument"; then
    : "BUG2 - An ASSIGNMENT cannot be made between reading FILEs"
    warn "WARNING: '$argument' will be assigned BEFORE opening any files"
    opts+=(-v "$argument")
  else
    set -- "$@" "$argument"
  fi
done

opts+=("$program_text") 	# append this after all variables

tmp="$(mktemp)" 	# this is solely to track the last byte of each input

for file in "${@:--}"; do
  : "file=$file"
  # add line break after files that lacked them
  if [ -z "$tmp" ] && [ "$(tail -c1 "$tmp")x" != $'\nx' ]; then
    printf $'\n'
  fi
  decompress "$file" |tee "$tmp"
done | "$awk" "${opts[@]}"

